# Generated by Django 4.2.7 on 2025-10-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
